### ISSUE TITLE
Line numbers.

### ISSUE THREAD

**Issue by van-de-bugger** [dagolden/Dist-Zilla-Plugin-Test-DiagINC#1]
`Test::DiagINC` is a great module, but it may be confusing because it adds a line to the test source and so, changes line numbers. It would be nice if `Test::DiagINC` keeps test source line numbers intact.

It can be easily achieved by replacing newline character with a blank:

    # original code:
    my $add = PPI::Token::Comment->new(
        q[use if $ENV{AUTOMATED_TESTING}, 'Test::DiagINC';] . "\n" );
    #                                                          ^^

    # modified code:
    my $add = PPI::Token::Comment->new(
        q[use if $ENV{AUTOMATED_TESTING}, 'Test::DiagINC';] . " " );
    #                                                          ^

**Comment by xdg** [comment]
Shipped 0.002 to CPAN
